### ISSUE TITLE
Changing bg color from grey to black doesn't cause test to fail

### ISSUE THREAD

**Issue by syntapy** [cypress-visual-regression/cypress-visual-regression#263]
# Overview

I get this with versions 5.0.4 and 5.0.3, unknown if on previous version

See my PR to demonstrate the issue here: https://github.com/syntapy/superformula_clone/pull/93

# Before / After images

No diff is generated from these two images

I did set the error threshold to 0

Fyi this is a clone website I'm working on for practice, not the actual Superformula website

| bg color = '#1a1a1a' | bg color = 'black' |
| --------------------| -------------------- |
|![bg color = '#1a1a1a'](https://github.com/user-attachments/assets/00aabe22-286b-4a96-80f3-08f874292f99) | ![bg color = 'black'](https://github.com/user-attachments/assets/aab51211-a0fe-4d03-bec3-580f7a6fa831)|

**Comment by syntapy** [comment]
Seems to be an issue as far back as 3.0.0, since in my temporary PR the mobile tests pass even with the bg color changed

**Comment by Zaista** [comment]
The reason for this is the sensitivity option for pixelMatch, currently it is set by default to 0.1 (https://github.com/mapbox/pixelmatch?tab=readme-ov-file#pixelmatchimg1-img2-output-width-height-options).

Since this difference is subtle and almost invisible to the naked eye, I wouldn't change the implementation.
What we could do though is expose this parameter so you can change it to 0 in your setup to hopefully achieve desired effect

**Comment by syntapy** [comment]
Could I give a at making the PR for this issue?

**Comment by Zaista** [comment]
Please do

**Comment by Zaista** [comment]
Hey @syntapy let's agree on how to continue, I'd like to be aware of the progress so that I can jump in if things don't work out. I see that your forked branch is quite out of date, so just let me know where/how you will be working on it.
Appreciate it 🙂

**Comment by Zaista** [comment]
Released in `v5.2.0`, there is a possibility now to change pixelmatch threshold sensitivity (or other options)
